let properties: Array<any> = [
    {
        id: 1,
        address: "M, Kanbaa Aisa Rani Hingun",
        city: "Male'",
        state: "Maafannu",
        zip: "20092",
        price: "Clinical trials",
        title: "Indira Gandi Memorial Hospital",
        bedrooms: "Antibiotics ",
        bathrooms: "Nasal polyp removal.",
        long: 73.501892,
        lat: 4.173536,
        picture: "http://www.islandmusicmaldives.com/wp-content/gallery/projects/igmh.jpg",
        thumbnail: "http://www.islandmusicmaldives.com/wp-content/gallery/projects/igmh.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
             picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 2,
        address: "M. Mishuru-ruvaage , Shariuvarudhee ",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "Lung Scans",
        title: "Azmi-Naeem Medical and Diagnostic Centre",
        bedrooms: "injection",
        bathrooms: "other",
        long: 73.503009,
        lat: 4.174277,
        picture: "http://www.bridgetravels.net/images/MaleCityMaldives.jpg",
        thumbnail: "http://www.bridgetravels.net/images/MaleCityMaldives.jpg",
        tags: "contemporary",
        description: "since 1992",
        broker: {
             id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
             picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 3,
        address: "Lily magu",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "appendency",
        title: "Maya Clinic",
        bedrooms: "cesarean",
        bathrooms: "chloecystecomy",
          long: 73.503267,
        lat: 4.172158,
        picture: "http://vnews-assets.s3-website-us-east-1.amazonaws.com/posts/medium_134996.jpg",
        thumbnail: "http://vnews-assets.s3-website-us-east-1.amazonaws.com/posts/medium_134996.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 4,
        address: "roashanee Magu",
        city: "Male",
        state: "Machan Golhi",
        zip: "02420",
        price: "breast biopsy",
        title: "Central medical Clinic",
        bedrooms: "anoplast",
        bathrooms: "aortic",
          long: 73.505970,
        lat: 4.175689,
        picture: "http://central.com.mv/wp-content/uploads/2014/04/slider-1.jpg",
        thumbnail: "http://central.com.mv/wp-content/uploads/2014/04/slider-1.jpg",
        tags: "victorian",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 5,
        address: "Iskandharu Magu",
        city: "Male",
        state: "Henveru",
        zip: "02420",
        price: "alveotror",
        title: "ADK Hospital",
        bedrooms: "bone grafting",
        bathrooms: "browlift",
          long: 73.506614,
        lat: 4.173913,
        picture: "http://www.geocities.jp/maldivestoday/1016adk03.jpg",
        thumbnail: "http://www.geocities.jp/maldivestoday/1016adk03.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 6,
        address: "Hilaalee Magu",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "bypass",
        title: "Primax Medi-care",
        bedrooms: "buttock",
        bathrooms: "eartube",
        long: 73.506939,
        lat: 4.172372,
        picture: "http://europeanclinicmaldives.net/onewebmedia/10.jpg",
        thumbnail: "http://europeanclinicmaldives.net/onewebmedia/10.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 7,
        address: "Maaveyo magu",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "endo surgery",
        title: "Advance medical clinic",
        bedrooms: "mion sergery",
        bathrooms: "enculation sergery",
          long: 73.509203,
        lat: 4.1732650,
        picture: "http://amdc.com.mv/wp-content/uploads/AMDC-Clinic.jpg",
        thumbnail: "http://amdc.com.mv/wp-content/uploads/AMDC-Clinic.jpg",
        tags: "colonial",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 8,
        address: "Voilet Magu",
        city: "Male",
        state: "Henveiru",
        zip: "02420",
        price: "kidney Scans,heart operations",
        title: "The Clinic",
        bedrooms: "Dermatology",
        bathrooms: "Pediatric allergy",
          long: 73.510712,
        lat: 4.173785,
        picture: "http://europeanclinicmaldives.net/onewebmedia/4.jpg",
        thumbnail: "http://europeanclinicmaldives.net/onewebmedia/4.jpg",
        tags: "victorian",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 9,
        address: "falhumathee magu",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "Nurology",
        title: "Imperial Clinic",
        bedrooms: "heart and surgery",
        bathrooms: "Vascular Surgery",
        long: 73.514210,
        lat: 4.172543,
        picture: "http://amdc.com.mv/wp-content/uploads/Physiotherapy.jpg",
        thumbnail: "http://amdc.com.mv/wp-content/uploads/Physiotherapy.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 10,
        address: "fareedheemagu",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "Hematology",
        title: "Medicare Medical Clinic",
        bedrooms: "Sepsis Initiative",
        bathrooms: "",
        long: 73.512751,
        lat: 4.175154,
        picture: "http://amdc.com.mv/wp-content/uploads/airportclinic.jpg",
        thumbnail: "http://amdc.com.mv/wp-content/uploads/airportclinic.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 11,
        address: "dhonadharaadha Hingun",
        city: "Male",
        state: "Maafannu",
        zip: "02420",
        price: "Early Life program",
        title: "Eve Clinic",
        bedrooms: "Urology",
        bathrooms: "Ophthalmology",
        long: 73.514360,
        lat: 4.173592,
        picture: "http://amdc.com.mv/wp-content/uploads/AMDC-Speciality-Clinic.jpg",
        thumbnail: "http://amdc.com.mv/wp-content/uploads/AMDC-Speciality-Clinic.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    },
    {
        id: 12,
        address: "Orchidmagu",
        city: "Male'",
        state: "MA",
        zip: "02420",
        price: "Eating Disorder Med",
        title: "Family Care",
        bedrooms: "Fit For health",
        bathrooms: "Cardiology",
          long: 73.507537,
        lat: 4.177637,
        picture: "http://amdc.com.mv/wp-content/uploads/Overview-of-operational-activities.jpg",
        thumbnail: "http://amdc.com.mv/wp-content/uploads/Overview-of-operational-activities.jpg",
        tags: "contemporary",
        description: "Lorem ipsum dolor sit amet",
        broker: {
            id: 1,
            name: "Ismail altaf",
            title: "CF Specialist",
            picture: "assets/img/DOC/ismail.jpg"
        }
    }
];

export default properties;
